import type { Metadata } from "next";
import { Geist, Kode_Mono } from "next/font/google";
import "./globals.css";
import { Button } from "@/components/ui/button";
import MainFooter from "@/components/MainFooter";
import LayoutClient from "./layout-client";
import Image from "next/image";

const kodeMono = Kode_Mono({
  variable: "--font-kode-mono",
  weight: ["400", "500", "600", "700"],
  subsets: ["latin"],
});

const geistFont = Geist({
  variable: "--font-geist",
  weight: ["400", "500", "600", "700"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${kodeMono.variable} ${geistFont.variable} antialiased`}
        style={{ fontFamily: 'var(--font-kode-mono)' }}
      >
        <LayoutClient>
          {/* --- Navbar --- */}
          <nav className="bg-background border-border fixed z-100 flex h-[60px] w-full items-center justify-between border-b p-2 text-white transition-colors duration-300 lg:px-6">
            <div className="flex items-center cursor-pointer">

              <Image loading="lazy" src="/logo.svg" alt="Logo" width={83} height={26} />
            </div>

            <div className="flex items-center">

              <Button className="nav-item block">Launch App</Button>

            </div>
          </nav>
          <main className="min-h-screen w-full overflow-x-clip">

            {children}
          </main>
          <MainFooter />
        </LayoutClient>
      </body>
    </html>
  );
}
